version: 0.0
os: linux

files:
- source: hello-0.0.1-SNAPSHOT.jar
  destination: /home/ec2-user/springboot-codedeploy-script-sample/target
  #- source: /
#  destination: /home/ec2-user

#permissions:
#  - object: /
#    pattern: "**"
#    owner: ec2-user
#    group: ec2-user

hooks:
  ApplicationStop:
    - location: scripts/server_stop.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/server_start.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/server_validate.sh
      timeout: 300
      runas: root