version: 0.2

phases:
    install:
        runtime-versions:
            java: corretto8
    pre_build:
        commands:
            - echo "Entered the pre-build phases"
            - echo "Frist step started"
    build:
        commands:
            - echo Build started on `date`
            - mvn clean package
    
    post_build:
        commands:
            - echo "Entered the post-build phases"
artifacts:
    files:
        - target/hello-0.0.1-SNAPSHOT.jar
        - appspec.yml
        - scripts/*
    discard-paths: yes