version: 0.2

#env:
#  variables:
#    JAVA_HOME: "/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.222.b10-0.amzn2.0.1.x86_64"
#    added few lines to check whether it will work or not

phases:
    install:
        runtime-versions:
            java: corretto11
    pre_build:
        commands:
            #- echo "Entered the pre-build phases"
            - echo "Frist step started"
    build:
        commands:
            - echo Build started on `date`
            - mvn clean package
    
    post_build:
        commands:
            - echo "Entered the post-build phases"
artifacts:
    files:
        - target/*.jar
        - scripts/*.sh
    discard-paths: yes
    
cache:
  paths:
  - '/root/.m2/**/*'